name = "Aaditya Vardhan Narain"
rol = "Software Developer"
email = "aaditya.narain.avna@gmail.com"
phone = ""
location = "Hyderabad, India"
avatar = "./config/assets/avatars/narain.jpg"
username = "Aaditya_Narain"
googlemaps = ""
presentation = "Hey There, if you stumbled onto this website then you are in for a treat, my name is Aaditya, you already know this i guess. Well Happy exploring the page. "
