# https://ionic.io/ionicons
# <ion-icon name="[[name]]"></ion-icon>
# name = "https://example.com/"


logo-instagram = "https://www.instagram.com/aaditya_narain/"
logo-linkedin = "https://www.linkedin.com/in/aaditya-vardhan-narain-9142581b5"
logo-github = "https://github.com/AadityaNarain2003"